config/routes.rb
Rails.application.routes.draw do

  root 'sessions#index'

  resources :users, only: [:create, :show, :edit, :update] do
    resources :accounts, only: [:new, :create, :index, :destroy]
    resources :stocks, only: [:index, :create]
    resources :shares
  end

  resources :accounts, only: [:show] do
    resources :transactions, only: [:new, :edit, :create, :destroy]
  end


  get '/highest', to: 'transactions#highest'
  get '/logout', to: 'users#destroy'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'

end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :bank
  has_many :accounts
  has_many :transactions, through: :accounts
  has_many :shares
  has_many :stocks, through: :shares
  has_secure_password
  # validates :username, :email, uniqueness: true
  # validates_presence_of :street_address, :city, :state, :email, :on => :create
  # validates :password, length: { minimum: 6, message: "must be at least 6 characters long"}
  # validates :zip_code, numericality: {only_integer: true, message: "can only be numbers"}
  # validates :zip_code, length: { is: 5 }
  # validates :first_name, :last_name, format: { with: /\A[a-zA-Z]+\z/,
  #   message: "Only letters allowed" }
  # validates :age, numericality: { greater_than_or_equal_to: 18 }


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:message] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    if logged_in? && current_user == @user

    else
      flash[:message] = "Access Denied: Invalid User"
      redirect_to '/'
    end
  end

  def edit
    @user = User.find(params[:id])
    if logged_in? && current_user == @user
    else
      flash[:message] = "Access Denied: Invalid User"
      redirect_to '/'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      flash[:message] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
      session.delete :user_id
      redirect_to '/'
  end

private

  def user_params
    params.require(:user).permit(:bank_id, :first_name, :last_name, :street_address, :city, :state, :zip_code, :age, :username, :email, :password)
  end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_accounts.html.erb
<% if @user.accounts.length > 0 %>
  <button id="user_accounts" data-id="<%= @user.id %>">View Accounts</button>
  <div class="accounts">
  </div><br>
<% else %>
  You have no opened accounts<br>
<% end %><br>
---------------------------------

app/views/users/_errorsforedit.html.erb
<% if flash[:message].is_a?(Array) %>
  <% flash[:message].each do |message| %>
    <%= message %><br>
  <% end %>
<% else %>
  <%= flash[:message] %>
<% end %><br>

app/views/users/_errorsforshow.html.erb
<p>
<% if flash[:message].is_a?(Array) %>
  <% flash[:message].each do |message| %>
    <%= message %>
  <% end %>
<% else %>
  <%= flash[:message] %>
<% end %>
</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <p>
    <%= f.label :bank, "Bank Name:" %>
    <%= f.collection_select(:bank_id, Bank.all, :id, :name, prompt: "Select a Bank") %>
  </p>

  <p>
    <%= f.label :first_name, "First Name:" %>
    <%= f.text_field :first_name, :placeholder => (@user.errors.full_messages_for(:first_name).first || "Enter First Name Here") %>
  </p>

  <p>
    <%= f.label :last_name, "Last Name:" %>
    <%= f.text_field :last_name, :placeholder => (@user.errors.full_messages_for(:last_name).first || "Enter Last Name Here") %>
  </p>

  <p>
    <%= f.label :street_address, "Street Address:" %>
    <%= f.text_field :street_address, :placeholder => (@user.errors.full_messages_for(:street_address).first || "Enter Address Here") %>
  </p>

  <p>
    <%= f.label :city, "City:" %>
    <%= f.text_field :city, :placeholder => (@user.errors.full_messages_for(:city).first || "Enter City Here") %>
  </p>

  <p>
    <%= f.label :state, "State:" %>
    <%= f.text_field :state, :placeholder => (@user.errors.full_messages_for(:state).first || "Enter State") %>
  </p>

  <p>
    <%= f.label :zip_code, "Zip Code:" %>
    <%= f.text_field :zip_code, :placeholder => (@user.errors.full_messages_for(:zip_code).first || "Enter Zip Code Here") %>
  </p>

  <p>
    <%= f.label :age, "Age:" %>
    <%= f.text_field :age, :placeholder => (@user.errors.full_messages_for(:age).first || "Enter Age Here") %>
  </p>

  <p>
    <%= f.label :username, "Username:" %>
    <%= f.text_field :username, :placeholder => (@user.errors.full_messages_for(:username).first || "Enter Username Here") %>
  </p>

  <p>
    <%= f.label :email, "Email:" %>
    <%= f.text_field :email, :placeholder => (@user.errors.full_messages_for(:email).first || "Enter Email Here") %>
  </p>

  <p>
    <%= f.label :password, "Password:" %>
    <%= f.password_field :password, :placeholder => (@user.errors.full_messages_for(:password).first || "Enter Password Here") %>
  </p>

  <%= f.submit %><br>
<% end %>

app/views/users/_stocks.html.erb
<% if @user.shares.length > 0 %>
<div class="stocks">
    <p>Company Name: <%= @user.shares[0].stock.company_name %><br>
      Shares: <%= @user.shares[0].quantity %><br>
      Equity: $<%= @user.shares[0].quantity * @user.shares[0].stock.price %></p>
</div>

<button id="previous_stock_browser" data-user_id="<%= @user.id %>">Previous</button>

<button id="stock_browser" data-user_id="<%= @user.id %>" data-share_index="0" data-share_length="<%= @user.shares.length %>"data-share_id='<%= @user.shares[0].id %>'>Next</button><br><br>
<% else %>
  You have no stocks right now<br><br>
<% end %>

app/views/users/edit.html.erb
<center>

<h1>Edit User Information</h1>

<%= render partial: "form" %><br>

<%= link_to "Home", '/' %><br>
<%= link_to "Log Out", logout_path %><br><br>

<%= render partial: "errorsforedit" %>

</center>

app/views/users/new.html.erb
<center>

<h1>Create New User</h1>

<%= render partial: "form" %>

<p>OR</p>

<p><%= link_to('Sign Up With Github', '/auth/github') %></p>

<%= link_to "Home", '/' %><br><br>

<% if flash[:message].is_a?(Array) %>
  <% flash[:message].each do |message| %>
    <%= message %><br>
  <% end %>
<% else %>
  <%= flash[:message] %>
<% end %>

</center>

app/views/users/show.html.erb
<center>

<h4><%= "#{@user.first_name} #{@user.last_name}"%></h4>

<%= render partial: "accounts" %>

<h4><%= "Your Stocks"%></h4>

<%= render partial: "stocks" %>

<%= link_to "View Stock Market", user_shares_path(@user) %><br><br>

<%= link_to "Open Account", new_user_account_path(@user) %><br>
<%= link_to "Manage Accounts", user_accounts_path(@user) %><br>

<%= link_to "User Settings", edit_user_path %><br><br>
<%= link_to "Log Out", logout_path %>

<%= render partial: "errorsforshow" %>

</center>