config/routes.rb
Rails.application.routes.draw do

  root 'sessions#index'

  resources :users, only: [:create, :show, :edit, :update] do
    resources :accounts, only: [:new, :create, :index, :destroy]
    resources :stocks, only: [:index, :create]
    resources :shares
  end

  resources :accounts, only: [:show] do
    resources :transactions, only: [:new, :edit, :create, :destroy]
  end


  get '/highest', to: 'transactions#highest'
  get '/logout', to: 'users#destroy'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'

end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :transactions
  validates :type_of_account, :balance, :user_id, presence: true
  validates :type_of_account, inclusion: { in: %w(Checking Savings Retirement), message: "You must enter a valid account type."}
  validates :balance, numericality: { greater_than_or_equal_to: 0, message: "must be a number and must be greater than or equal to $0"}, on: :create

  def self.types_for_form
    %w[Checking Savings Retirement]
  end


end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
    @account = Account.new
    @user = User.find(params[:user_id])
    if logged_in? && current_user == @user
    else
      flash[:message] = "Access Denied: Invalid User"
      redirect_to '/'
    end
  end

  def create
    @user = User.find(params[:user_id])
    if logged_in? && current_user == @user
      @account = @user.accounts.build(account_params)
      if @account.save
        redirect_to user_path(@user)
      else
        render :new
      end
    else
      flash[:message] = "Access Denied: Invalid User"
      redirect_to '/'
    end
  end

  def index
    @user = User.find(params[:user_id])
    @accounts = @user.accounts
    if logged_in? && current_user == @user
      respond_to do |format|
        format.html
        format.json {render json: @accounts}
      end
    else
      flash[:message] = "Access Denied: Invalid User"
      redirect_to '/'
    end
  end

  def destroy
    @account = Account.find(params[:id])
    @user = User.find(params[:user_id])
    @account.delete
    redirect_to user_accounts_path(@user)
  end

  def show
    @account = Account.find(params[:id])
    @user = @account.user
    @transactions = @account.transactions
    @transaction = @user.transactions.build
    if logged_in? && current_user == @user
    else
      flash[:message] = "Access Denied: Invalid User"
      redirect_to '/'
    end
  end

  private

  def account_params
    params.require(:account).permit(:type_of_account, :balance, :user_id)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper


end

app/views/accounts/_accounts.html.erb
<% if @accounts.length > 0 %>

<% @accounts.each do |account| %>
  <p><b><%= account.type_of_account %></b></p><%="$#{account.balance}" %><br><br>
  <%= link_to "Close Account", user_account_path(@user, account), data: {confirm: "Are you sure you want to close this account? Your balance will be lost forever!"}, method: :delete %><br>
<% end %>

<% else %>

You have no accounts<br>
<% end %>

app/views/accounts/index.html.erb
<center>
<%= render partial: "accounts" %>
<p><%= link_to "Home", '/' %><br>
<%= link_to "Log Out", logout_path %></p>

</center>

app/views/accounts/new.html.erb
<center>

<h1>Open Account</h1>

<%= form_for([@user, @account]) do |f| %>
  <%= f.label :type_of_account, "Account Type" %><br>
  <p><%= f.select :type_of_account, options_for_select(Account.types_for_form, @account.type_of_account) %></p>
  <p>
    <%= f.label :balance, "Initial Deposit " %><br><br>
    $ <%= f.text_field :balance %>
  </p>
  <%= f.hidden_field :user_id, :value=> @user.id %>
  <%= f.submit %>
<% end %><br>

<%= link_to "Home", '/' %><br>
<%= link_to "Log Out", logout_path %>

<% if flash[:message] %>
   <h3><%= flash[:message] %></h3>
<% end %>

</center>

app/views/accounts/show.html.erb
<center>

  <h1><%= "#{@account.type_of_account} Account" %></h1>

  <h3>Current Balance</h3>
  <p><%= "$#{@account.balance}" %></p>

  <h3>Transaction History</h3>

<div class="transactions">
  <% @transactions.each do |transaction| %>
  <% if transaction.processed == false %>
    <%= transaction.type_of_transaction %><br>
    $<%= transaction.amount %><br>
    <%= link_to "Process", edit_account_transaction_path(@account, transaction) %><br><br>
  <% end %>
  <% end %>
</div><br>


<button class="transaction-link">Quick Transaction</button><br><br>

<div class="quickTransactionForm" style="display: none">
  <%= form_for([@account, @transaction]) do |f| %>
    <%= f.hidden_field :account_id, :value => @account.id %>
    <%= f.hidden_field :user_id, :value=> @account.user_id %>
    <%= f.label :type_of_transaction, "Choose Your Transaction:" %><br>
    <p><%= f.select :type_of_transaction, options_for_select(Transaction.types_for_form, @transaction.type_of_transaction) %></p>
    <%= f.label :amount, "Amount (Minimum is $1)" %>
    <p> <%= f.text_field :amount, :placeholder => (@transaction.errors.full_messages_for(:amount).first || "Enter Amount Here")%>
    </p>
    <%= f.submit :id => 'createTransaction'%>
  <% end %>
</div>

<br><%= link_to "Home", user_path(@account.user_id)%><br>
<%= link_to "Log Out", logout_path %></p>




</center>